### ISSUE TITLE
Linq erros.

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#114] opened 2020-01-10 13:28 UTC
I am having lots of errors with version 3 on simple querys lique this

(1 + (detalheArmazem.Artigo.Iva.Taxas.OrderByDescending(c => c.Data).First(c => c.Data <= AppHelper.Variaveis.DataTrabalho).Acores));

I this you have new ways in linq, is think that it has something to do with OrderBy clause.

**Comment by rivantsov** [comment] 2020-01-10 14:10
what kind of errors? it does not compile, does not translate to SQL, or makes invalid sql? pls be more specific

**Comment by rubenalves** [comment] 2020-01-10 14:45
It compiles very well. The aplication now runs, only on some operations it gives a runtime error like the error below:
Destination array was not long enough. Check destIndex and length, and the array's lower bounds.

**Comment by rubenalves** [comment] 2020-01-10 14:47
System.ArgumentException
  HResult=0x80070057
  Message=A matriz de destino não era suficientemente longa. Verifique destIndex, o comprimento e os limites inferiores da matriz.
  Source=mscorlib
  StackTrace:
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at TsGest.DL.Helper.ArtigoHelper.TaxaIva(IDetalheArmazem detalheArmazem) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest.DL\Helper\ArtigoHelper.cs:line 355
   at TsGest.DL.Helper.ArtigoHelper.RemoverPVP1(IDetalheArmazem detalheArmazem, Boolean todos) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest.DL\Helper\ArtigoHelper.cs:line 253
   at TsGest.BL.ModelView.Artigos.EditorArtigosViewModel.set_PVP1(Decimal value) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest.BL\ModelView\Artigos\EditorArtigosViewModel.cs:line 313

**Comment by rivantsov** [comment] 2020-01-10 19:43
what is Taxas in the Linq expression? entity list property on Iva entity? Can you pls post both entity definitions? the error does not look like related to SQL or any db activity, pure Linq operation over lists in memory

**Comment by rubenalves** [comment] 2020-01-10 20:15
Taxas is a list of entites
Here are the 2 files.
[IVA.txt](https://github.com/rivantsov/vita/files/4047748/IVA.txt)
[IVATaxa.txt](https://github.com/rivantsov/vita/files/4047749/IVATaxa.txt)
I think that it has to do with the tables not being cached in memory.

**Comment by rubenalves** [comment] 2020-01-11 10:46
I foud a potencial problem.

if i do lique this
--------
var emp = _session.GetEntity<IEmpresa>(1);
var ent = _session.GetEntity<IEntidade>(Documento.Entidade.ID);
MoradasCarga = ent.Moradas; 
---- it works
if i do: 
-----
MoradasCarga = _session.GetEntity<IEmpresa>(1).Entidade.Moradas.ToList();
-----
it gives error:
System.ArgumentException: 'A matriz de destino não era suficientemente longa. Verifique destIndex, o comprimento e os limites inferiores da matriz.'

Thanks.

**Comment by rivantsov** [comment] 2020-01-11 16:23
Interesting.. all I could find about this error, when it happens inside Linq ops like this, is that likely it is related to threading and multi-threading, it might happen when more than one thread accesses 'the list'. What is your 'environment'? is this code called from inside 'button-click' of some desktop (WPF?) app? or is it web app? Can you pls show more of the calling code, how the _session is opened?
Next, this error - it happens consistently 100% of the time, or some of the times?

**Comment by rubenalves** [comment] 2020-01-11 16:43
The aplication is WinForms app, it is on a single thread,
I will join the ViewModel that runs the code.
[EditorDocumentos.txt](https://github.com/rivantsov/vita/files/4049537/EditorDocumentos.txt)
It happens every time.

**Comment by rivantsov** [comment] 2020-01-11 17:03
in the code above, with 2 fragments that work and don't work - if in the first fragment that works, what if you append ToList(): 
MoradasCarga = ent.Moradas.ToList();

does this work?
also, in form listing you posted, what is missing is code that opens session in _session variable

**Comment by rubenalves** [comment] 2020-01-11 17:19
I use EmpresaAtual.SessionFactory.OpenSession(); to open session.
MoradasCarga = ent.Moradas.ToList();
gives the same error, so that may be the problem.

**Comment by rivantsov** [comment] 2020-01-11 17:52
SessionFactory? it is not fwk class, it is your class, so pls show details. 
Also, with this ToList() error - pls post stack trace

**Comment by rivantsov** [comment] 2020-01-11 18:16
also, IEntidade.Moradas - is one-to-many or many2many list?

**Comment by rubenalves** [comment] 2020-01-11 18:25
public OperationContext SessionFactory { get; set; }
It ia a classe i made.
IEntidade.Moradas as one-to-many 

The stack trace is:
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TsGest.BL.ModelView.Documentos.EditorDocumentoViewModel..ctor(Guid id, String serie, IDocumento docTransfer, ILinhaDocumento linha, Boolean mesmoTerceiro, Boolean ligarDoc) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest.BL\ModelView\Documentos\EditorDocumentoViewModel.cs:line 94
   at TsGest.NewForms.Documentos.formEditorDocumentos..ctor(Guid id, String serie, IDocumento docTransfer, ILinhaDocumento linha, Boolean mesmoTerceiro, Boolean ligarDoc) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest\NewForms\Documentos\formEditorDocumentos.cs:line 34
   at TsGest.Forms.FormsHelper.CriarDocumentoMain(RibbonForm parent, String serie, String designcao) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest\Forms\FormsHelper.cs:line 44
   at TsGest.NewForms.TsMainForm.NovoDocumento(String serie, String designacao) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest\NewForms\TsMainForm.cs:line 418
   at TsGest.NewForms.TsMainForm.btnNovaFT_ItemClick(Object sender, ItemClickEventArgs e) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest\NewForms\TsMainForm.cs:line 413
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnUnPressItem(DXMouseEventArgs e, RibbonHitInfo hitInfo)
   at DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnMouseUp(DXMouseEventArgs e)
   at DevExpress.XtraBars.Ribbon.Handler.RibbonHandler.OnMouseUp(DXMouseEventArgs e)
   at DevExpress.XtraBars.Ribbon.RibbonControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraBars.Ribbon.RibbonControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rivantsov** [comment] 2020-01-11 18:41
reproduced! can't believe it, that never ran into this before. Will fix
thanks and sorry for trouble

**Comment by rubenalves** [comment] 2020-01-11 19:10
Thank you for all the trobles i am giving you.

I have another error that i do not know it it is related.
Unable to associate object of type 'Vita.Entities.Runtime.PropertyBoundListManyToOne`1 [TsGest.DL.Domain.IPFreedomCCEnt]' with type 'TsGest.DL.Domain.IPrefixCCEntity'.

It is winforms bindingsource
PrefixoCC = (IPrefixoCCEntidade)Prefixos.Current;

PrefixoCC is of type of IPrefixoCCEntidade - It is a cast from one object to another
Thanks.

**Comment by rubenalves** [comment] 2020-01-13 23:58
Foud a new error and it dos not use ToList()
 return taxa.OrderByDescending(c => c.Data).First().Acores;
It may be related.
Will continue to find new places with error.
Thanks.

**Comment by rivantsov** [comment] 2020-01-14 00:02
thanks, but it's the same bug, will fix it asap

**Comment by rivantsov** [comment] 2020-01-14 02:33
sorry, did not mean to close it yet, github did it when bug # was mentioned in checkin
So, it should be fixed now, nuget packages pushed, v 3.0.2

**Comment by rubenalves** [comment] 2020-01-14 20:33
The previous error is fine, i found a nde one, 
[Column(DbTypeSpec = "Decimal", Scale = 2, Precision = 5)]
decimal Acores { get; set; }
The database columns gets created as (decimal(18,0), not null)

Whar is the correct form to create this type of columns?
Thanks.

**Comment by rubenalves** [comment] 2020-01-14 20:54
If i remove DBTypeSpec it gets created 
as (decimal(5,2), not null)
I will change my code.
Thanks.

**Comment by rivantsov** [comment] 2020-01-14 20:58
yeah, that's because explicit type spec overwrites all other type mapping paths

**Closed by rivantsov** 2020-01-14 20:58 UTC
