### ISSUE TITLE
Linq SelectMany is not working

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#164] opened 2021-02-12 02:00 UTC
Hi,

I have Entity relationship BillingAccount -< BillingType -< BillingUnit, where "-<" denotes 1-many relationship.

With 2 records of BillingType and each has 5 BillingUnit, I expect the following linq will return me 10 entities of BillingUnit.

~~~c#
var billingUnits = billingAccount.BillingTypes.SelectMany(x => x.BillingUnits).ToList();
~~~

In reality, it returns me 10 entities, with 5 of if are null value.
I believe this is a bug due to the lazy loading.

~~~c#
?billingUnits
Count = 10
    [0]: {IBillingUnit/00001-00001/Loaded}
    [1]: {IBillingUnit/00001-00002/Loaded}
    [2]: {IBillingUnit/00001-00003/Loaded}
    [3]: {IBillingUnit/00001-00004/Loaded}
    [4]: {IBillingUnit/00001-00005/Loaded}
    [5]: null
    [6]: null
    [7]: null
    [8]: null
    [9]: null
~~~

**Comment by rivantsov** [comment] 2021-02-12 02:18
Hi, the first thing to do in cases like this - look at SQL in log, this should give some clues; pls post it here

**Comment by jasonlaw** [comment] 2021-02-12 03:18
---------------------------------------------------------------------------------------
POST: http://localhost:5000/api/billing/generate
{"title":"string","description":"string"}
User: jasonlaw
SELECT  "Key", "LoginId", "PasswordHash", "PasswordSalt", "Flags", "LastSuccessOn", "CreatedOn", "AuthPin", "IsSystemAdmin"
FROM "communityv3staging"."Auth"
WHERE "LoginId" = @P0
 LIMIT 1 OFFSET 0 ; 
-- Parameters: @P0='jasonlaw' 
 -- Time 15.8566 ms; 1 row(s), [2021/02/12 03:17:41] 

SELECT  "Id", "Name", "PhoneNumber", "Email", "AppToken", "OfficerPassword", "Auth_Key", "Picture_Key", "Member_Key", "Vendor_Id", "OfficerCommunity_Id", "OfficerPatrol_Id"
FROM "communityv3staging"."User"
WHERE "Id" = @P0
 LIMIT 1 OFFSET 0 ; 
-- Parameters: @P0='jasonlaw' 
 -- Time 8.3289 ms; 1 row(s), [2021/02/12 03:17:41] 

SELECT  "Key", "Admin", "Address", "DisableNotification", "Inactive", "InactiveBy", "InactiveOn", "User_Id", "Community_Id"
FROM "communityv3staging"."MemberInCommunity"
WHERE "Key" = @P0; 
-- Parameters: @P0='01CDD7EC79482D4785992DF1E897837B' 
 -- Time 8.4195 ms; 1 row(s), [2021/02/12 03:17:41] 

SELECT  "Id", "Email", "Active", "TransactionFee", "Community_Id"
FROM "communityv3staging"."BillingAccount"
WHERE ("Id" = @P0 OR ("Id" IS NULL) AND (@P0 IS NULL)); 
-- Parameters: @P0='00001' 
 -- Time 7.9313 ms; 1 row(s), [2021/02/12 03:17:41] 

------- Running include queries   ----------
------- Completed include queries ----------
SELECT  "Id", "Code", "Name", "Fee", "Community_Id", "BillingAccount_Id"
FROM "communityv3staging"."BillingType"
WHERE ("BillingAccount_Id" = @P0 OR ("BillingAccount_Id" IS NULL) AND (@P0 IS NULL)); 
-- Parameters: @P0='00001' 
 -- Time 7.9838 ms; 2 row(s), [2021/02/12 03:17:41] 

------- Running include queries   ----------
------- Completed include queries ----------
SELECT  "Id", "Address", "Community_Id", "BillingType_Id", "BillingAccount_Id", "Owner_Key"
FROM "communityv3staging"."BillingUnit"
WHERE ("BillingType_Id" = @P0 OR ("BillingType_Id" IS NULL) AND (@P0 IS NULL)); 
-- Parameters: @P0='00001-A' 
 -- Time 7.9598 ms; 5 row(s), [2021/02/12 03:17:41] 

------- Running include queries   ----------
------- Completed include queries ----------
SELECT  "Id", "Address", "Community_Id", "BillingType_Id", "BillingAccount_Id", "Owner_Key"
FROM "communityv3staging"."BillingUnit"
WHERE ("BillingType_Id" = @P0 OR ("BillingType_Id" IS NULL) AND (@P0 IS NULL)); 
-- Parameters: @P0='00001-B' 
 -- Time 7.9034 ms; 5 row(s), [2021/02/12 03:17:41] 

------- Running include queries   ----------
------- Completed include queries ----------

Response status: OK, bytes: 0, duration: 131 ms

**Comment by rivantsov** [comment] 2021-02-12 03:47
Looks like the last query brings NULLs. Just copy it into Sql mgt studio (or whatever tool you use to access db data) and run the last query, just declare @p0 variable and assign it '00001-B'. See what it brings.  I suspect there are some null-filled orphan records there. 

Now, one strange thing I see. Notice in last 3 queries, for BillingType and BillingUnit, this strange WHERE clause with NULLs.
I appears that columns BillingType.BillingAccount_ID and BillingUnit.BillingType_id are Nullable. Which is a bit strange arrangement.  If BillingType is child of BillingAccount, and it is since you have BillingTypes property on BillingAccount entity - then its FK column to parent must NOT be nullable. Otherwise there might be surprises... same for BillingUnit link to BillingType. I would suggest to have a second look at this. What is the purpose? If BillingType or BillingUnit have NULL in these FK to parent columns, the records are ORPHANs - does it have some biz meaning? 
This kind of WHERE expr with NULLs check is strange in this situation, it should never come up in these parent-child relationships. It is mainly to search for records with some value in a column, and to allow this searched value to be NULL - the engine makes this extra expr with NULLs, because NULL=NULL is always false in SQL.

**Comment by jasonlaw** [comment] 2021-02-12 04:25
![image](https://user-images.githubusercontent.com/107820/107730029-64618280-6d2d-11eb-88af-a7ced07eaf1b.png)


As for the null reference, I am not too sure if I follow, anyway here is my entity model.

~~~C#
    [Entity]
    [Display("{Id} - {Email}")]
    public interface IBillingAccount : ICommunityTable
    {
        [PrimaryKey, Size(10)]
        string Id { get; set; }

        [Size(Sizes.Email)] 
        string Email { get; set; } 
       
        bool Active { get; set; }

        int TransactionFee { get; set; }

        IList<IBillingType> BillingTypes { get; }

        IList<IBillingUnit> BillingUnits { get; }
        
        IList<IBillingCollection> BillingCollections { get; }       
    }

    [Entity]
    [Display("{Id}")]
    public interface IBillingType : ICommunityTable
    {
        [PrimaryKey, Size(10)]
        string Id { get; set; }

        [Size(4)]
        string Code { get; set; }

        [Size(Sizes.Name)]
        string Name { get; set; }
        
        int Fee { get; set; }

        IBillingAccount BillingAccount { get; set; }

        IList<IBillingUnit> BillingUnits { get; }
    }

    [Entity]
    public interface IBillingUnit : ICommunityTable
    {
        [PrimaryKey, Size(20)]
        [AutoSequenceNumber(tag: ContextTag.CommunityId)] //eg, 00001-0001
        string Id { get; }

        //ICommunity Community { get; set; }

        [Size(100)]
        string Address { get; set; }

        IBillingType BillingType { get; set; }
        
        IBillingAccount BillingAccount { get; set; }

        IList<IBillingInvoice> BillingInvoices { get; set; }

        [Nullable]
        IMemberInCommunity Owner { get; set; }
    }
~~~

**Comment by rivantsov** [comment] 2021-02-12 04:26
btw, I think it has nothing to do with selectMany... child records are queried separately and then joined on client side.

**Comment by rivantsov** [comment] 2021-02-12 04:31
ah, ok, now I get it, it is because your PK column is string.. let me look into this, looks strange

**Comment by rivantsov** [comment] 2021-02-12 04:54
ok, let's just try to do it without select many, lets check the child list of the second billing type: 

var billingUnits2 = billingAccount.BillingTypes[1].BillingUnits;

and print it
and check SQLs

**Comment by jasonlaw** [comment] 2021-02-14 03:52
~~~C#
var billingUnits2 = billingAccount.BillingTypes[1].BillingUnits;
foreach( var unit in billingUnits2)
{
    System.Console.WriteLine($"Billing Unit >> {unit.Id}");
}
~~~

Output:
Registration completed for site "VIQCore.Community"
IIS Express is running.
Billing Unit >> 00001-00006
Billing Unit >> 00001-00007
Billing Unit >> 00001-00008
Billing Unit >> 00001-00009
Billing Unit >> 00001-00010

SQL Log:
~~~C#
 ======== Log Started 2/14/2021 3:48:48 AM ============
SELECT  "Key", "LoginId", "PasswordHash", "PasswordSalt", "Flags", "LastSuccessOn", "CreatedOn", "AuthPin", "IsSystemAdmin"
FROM "communityv3staging"."Auth"
WHERE "LoginId" = @P0
 LIMIT 1 OFFSET 0 ; 
-- Parameters: @P0='support@viqcore.com' 
 -- Time 20.0738 ms; 1 row(s), [2021/02/14 03:48:52] 


---------------------------------------------------------------------------------------
POST: http://localhost:5000/api/billing/generate
{"title":"string","description":"string"}
User: jasonlaw
SELECT  "Key", "LoginId", "PasswordHash", "PasswordSalt", "Flags", "LastSuccessOn", "CreatedOn", "AuthPin", "IsSystemAdmin"
FROM "communityv3staging"."Auth"
WHERE "LoginId" = @P0
 LIMIT 1 OFFSET 0 ; 
-- Parameters: @P0='jasonlaw' 
 -- Time 17.3884 ms; 1 row(s), [2021/02/14 03:49:12] 

SELECT  "Id", "Name", "PhoneNumber", "Email", "AppToken", "OfficerPassword", "Auth_Key", "Picture_Key", "Member_Key", "Vendor_Id", "OfficerCommunity_Id", "OfficerPatrol_Id"
FROM "communityv3staging"."User"
WHERE "Id" = @P0
 LIMIT 1 OFFSET 0 ; 
-- Parameters: @P0='jasonlaw' 
 -- Time 8.8819 ms; 1 row(s), [2021/02/14 03:49:13] 

SELECT  "Key", "Admin", "Address", "DisableNotification", "Inactive", "InactiveBy", "InactiveOn", "User_Id", "Community_Id"
FROM "communityv3staging"."MemberInCommunity"
WHERE "Key" = @P0; 
-- Parameters: @P0='01CDD7EC79482D4785992DF1E897837B' 
 -- Time 8.683 ms; 1 row(s), [2021/02/14 03:49:13] 

SELECT  "Id", "Email", "Active", "TransactionFee", "Community_Id"
FROM "communityv3staging"."BillingAccount"
WHERE ("Id" = @P0 OR ("Id" IS NULL) AND (@P0 IS NULL)); 
-- Parameters: @P0='00001' 
 -- Time 8.5306 ms; 1 row(s), [2021/02/14 03:49:13] 

------- Running include queries   ----------
------- Completed include queries ----------
SELECT  "Id", "Code", "Name", "Fee", "Community_Id", "BillingAccount_Id"
FROM "communityv3staging"."BillingType"
WHERE ("BillingAccount_Id" = @P0 OR ("BillingAccount_Id" IS NULL) AND (@P0 IS NULL)); 
-- Parameters: @P0='00001' 
 -- Time 7.8827 ms; 2 row(s), [2021/02/14 03:49:13] 

------- Running include queries   ----------
------- Completed include queries ----------
SELECT  "Id", "Address", "Community_Id", "BillingType_Id", "BillingAccount_Id", "Owner_Key"
FROM "communityv3staging"."BillingUnit"
WHERE ("BillingType_Id" = @P0 OR ("BillingType_Id" IS NULL) AND (@P0 IS NULL)); 
-- Parameters: @P0='00001-B' 
 -- Time 9.777 ms; 5 row(s), [2021/02/14 03:49:13] 

------- Running include queries   ----------
------- Completed include queries ----------

Response status: OK, bytes: 0, duration: 143 ms
~~~

**Comment by rivantsov** [comment] 2021-02-14 04:23
ok, that's really weird, it works correctly in this case. I will try to repro it on some sample schema and let you know
for now looks like you have a workaround, bit annoying but smth that works

**Comment by rivantsov** [comment] 2021-02-14 07:50
reproduced, it's a bug; don't know what the problem is yet, but will be fixing it asap

**Comment by rivantsov** [comment] 2021-02-15 03:15
fixing this and couple of other issues, will push soon, sources and packages

**Comment by rivantsov** [comment] 2021-02-17 07:16
should be fixed now

**Closed by rivantsov** 2021-02-17 07:16 UTC
