### ISSUE TITLE
Problems converting to 3.0

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#111] opened 2020-01-06 17:34 UTC
I am having a problem converting my app,
This is one of the errors
var loginService = empresa.Aplicacao.GetService(); service does not exist.
Another one is
[Column(DbType = DbType.Date)]
id not correct, what is the new sintax?

Thanks.

**Comment by rubenalves** [comment] 2020-01-06 17:35
[Column(DbTypeSpec = "Date")]

**Comment by rubenalves** [comment] 2020-01-06 17:42
Is this the correct usage?
 [Column(DbTypeSpec = "Date")]

**Comment by rubenalves** [comment] 2020-01-06 17:43
Sorry,
I am converting from 1.9.3.

**Comment by rivantsov** [comment] 2020-01-06 17:51
About DBTypeSpec - yes, that's the correct way, DbType not used anymore
as for GetService - 
use entityApp.LogService property

**Comment by rubenalves** [comment] 2020-01-06 18:53
I have a new Problem.

public class ArtigosController : SlimApiController
This is not working.
Thanks.

**Comment by rubenalves** [comment] 2020-01-06 18:59
Another one

[Unique("Serie,Numero,Ano,Loja", IndexName = "idx_SerieNumeroAno")]

IndexName is not available any more.

**Comment by rivantsov** [comment] 2020-01-06 19:11
SlimApiController - this is not there anymore, you should derive from BaseApiController in Vita.Web, look at Samples.BookStore.Api project; note that if you had controllers in the same assembly as entity app (used to be like that with SlimApi) - now **you have to put controllers into a separate project (ASP.NET core web api project) that references Vita.Web**. Sorry, had to abandon this approach with slim api controllers that are regular .net classes and do not depend on web stuff. 
IndexName changed to DBKeyName

**Comment by rubenalves** [comment] 2020-01-06 20:49
Are this still nessesary?

App.CacheSettings.CacheEnabled = true;
            App.CacheSettings.FullSetCacheTypes.Add(typeof(IUnidade));
            App.CacheSettings.LocalSparseCacheTypes.Add(typeof(ICaixa));
            App.CacheSettings.FullSetCacheTypes.Add(typeof(IIva));
            App.CacheSettings.FullSetCacheTypes.Add(typeof(IIvaTaxa));

It is diving erros.
Tanks.

**Comment by rivantsov** [comment] 2020-01-06 20:50
no, data cache is not migrated

**Comment by rubenalves** [comment] 2020-01-06 20:51
Ok.

**Comment by rubenalves** [comment] 2020-01-06 21:05
var driver = new MsSqlDbDriver(MsSqlVersion.V2012);
                DbSettings = new DbSettings(driver, MsSqlDbDriver.DefaultMsSqlDbOptions, connectionString, upgradeMode: DbUpgradeMode.Always);

Waht is the new syntaks for this, i canot find it,
in SQLLite got ut, in mssql no.
Thans

**Comment by rivantsov** [comment] 2020-01-06 21:10
just remove version parameter from new MsSqlDbDriver, everything else should be the same

**Comment by rubenalves** [comment] 2020-01-06 21:20
Sorry tho so may questions.

This is not leagal
App.GetService<IDataAccessService>().Events.DataSourceStatusChanging += EventsOnDataSourceChange;
it is used to monitor db updates on my app.

Thanks.

**Comment by rubenalves** [comment] 2020-01-06 21:28
var loginService = AppHelper.EmpresaAtual.Aplicacao.GetService<ILoginService>();
.....
if (resultado.Status == LoginAttemptStatus.Success)
            {
                AppHelper.UserNameLogin = UserName;
                AppHelper.PasswordLogin = Password;
......
using Vita.Modules.Login; 
not available anymore.
Thanks.

**Comment by rubenalves** [comment] 2020-01-06 21:30
var loginService = AppHelper.EmpresaAtual.Aplicacao.GetService<ILoginService>();
Sory

**Comment by rubenalves** [comment] 2020-01-06 21:30
var loginService = AppHelper.EmpresaAtual.Aplicacao.GetService < ILoginService > ();

**Comment by rivantsov** [comment] 2020-01-06 21:37
DataSourceStatusChange - use 
app.DataSourceEvents.DataSourceChange += ..

Vita.Modules.Login - you should install nuget package Vita.Modules.Login

**Comment by rivantsov** [comment] 2020-01-06 21:39
about DataSourceChange event - you say you used it to monitor db updates? but it signals CHANGES to database connection status as a whole, like when you just connected to database

**Comment by rubenalves** [comment] 2020-01-06 23:02
using Vita.Modules.EncryptedData;
where is this located?
Vita.Web ? Vita.Data?

Thanks.

**Comment by rivantsov** [comment] 2020-01-06 23:07
Vita.Modules.Legacy package
Advise: open  sources, VitaCoreAll solution, keep it open, and search for things like this using Find facility; there are also all sorts of examples of use there

**Comment by rubenalves** [comment] 2020-01-07 13:26
I have almost everything working

I have this code
session.EntitySet<IAcumuladosContaSNC>().ExecuteDelete<IAcumuladosContaSNC>();
it is not possible now?
Any other way to do it?
Thanks.

**Comment by rubenalves** [comment] 2020-01-07 15:08
I am geting a error
Build Entity Model Failed error, how do i know what is not ok, it is very generic error. Probably a column i changed because of the conversion, but i do nor kown what column.
Thanks.

**Comment by rivantsov** [comment] 2020-01-07 15:10
it is removed, for safety reasons, it was too easy  and dangerous, one run it by accident
use a bit more long version: 
var queryToDelete = session.EntitySet<IEnt>();
session.ExecuteDelete<IEnt>(queryToDelete); 

Build entity mode failed - catch the exception and inspect the details inside, there must be list of errors there; or try printout exc.ToLogString();

**Comment by rubenalves** [comment] 2020-01-07 18:27
[Nullable, Column(DbTypeSpec = "Time")]
        TimeSpan HoraDescarga { get; set; }

Is this the correct form for Time column?
I suspect that the error building the model is because of this.
Thanks.

**Comment by rivantsov** [comment] 2020-01-07 18:31
try to catch the exc and see the details, all explanation should be there. 
as for time type, according to this: 
https://www.sqlservertutorial.net/sql-server-basics/sql-server-time/

it should be "Time(0)", try it

**Comment by rubenalves** [comment] 2020-01-07 21:55
The problem is with byte[]
---- Old
[Column(DbType = DbType.Binary), Nullable, Unlimited]
byte[] ImagemStore { get; set; }
----New
[Column(DbTypeSpec = "Binary"), Nullable, Unlimited]
byte[] ImagemStore { get; set; }

does not build model because of this.
Thanks.

**Comment by rubenalves** [comment] 2020-01-07 22:23
New Error:

Vita.Entities.DataAccessException
  HResult=0x80131500
  Message=Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.
  Source=Vita
  StackTrace:
   at Vita.Data.Runtime.Database.ExecuteDataCommand(DataCommand command)
   at Vita.Data.Runtime.Database.SaveTableGroupRecordsOneByOne(DbUpdateTableGroup tableGrp, DataConnection conn, DbUpdateSet updateSet)
   at Vita.Data.Runtime.Database.SaveChangesNoBatch(DbUpdateSet updateSet)
   at Vita.Data.Runtime.Database.SaveChanges(EntitySession session)
   at Vita.Entities.Runtime.EntitySession.SubmitChanges()
   at Vita.Entities.Runtime.EntitySession.SaveChanges()
   at TsGest.DL.SeedData.LojaData.Inserir() in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest.DL\SeedData\LojaData.cs:line 39
   at TsGest.DL.SeedData.Seed.InserirDados(Boolean sqlLite) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest.DL\SeedData\Seed.cs:line 37
   at TsGest.DL.InicializarDataLayer.Inicializar(String nomeBaseDados, String caminho) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest.DL\InicializarDataLayer.cs:line 112
   at TsGest.DL.InicializarDataLayer.DataLayer(String server, String nomeDataBase, String userName, String password, String caminho) in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest.DL\InicializarDataLayer.cs:line 46
   at TsGest.frmSplash.Inicializar() in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest\frmSplash.cs:line 46
   at TsGest.frmSplash.<frmSplash_Shown>b__3_0() in C:\Dropbox\TerceiraSoft\2020\TsGest\TsGest\frmSplash.cs:line 34
   at System.Threading.Tasks.Task.Execute()

  This exception was originally thrown at this call stack:
	System.Data.SqlClient.SqlConnection.OnError(System.Data.SqlClient.SqlException, bool, System.Action<System.Action>)
	System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject, bool, bool)
	System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject, out bool)
	System.Data.SqlClient.SqlCommand.FinishExecuteReader(System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.RunBehavior, string, bool, bool, bool)
	System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, bool, bool, int, out System.Threading.Tasks.Task, bool, bool, System.Data.SqlClient.SqlDataReader, bool)
	System.Data.SqlClient.SqlCommand.RunExecuteReader(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, bool, string, System.Threading.Tasks.TaskCompletionSource<object>, int, out System.Threading.Tasks.Task, out bool, bool, bool)
	System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(System.Threading.Tasks.TaskCompletionSource<object>, string, bool, int, out bool, bool, bool)
	System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
	Vita.Data.Driver.DbDriver.ExecuteCommand(System.Data.IDbCommand, Vita.Data.DbExecutionType)

Inner Exception 1:
SqlException: Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.

**Comment by rivantsov** [comment] 2020-01-08 01:01
about first problem, DbTypeSpec = "Binary" - this is invalid, just remove the Column attribute, fwk should assign the correct type 
the second error - looks like you have type mismatch on some property, likely string property but DbTypeSpec is 'varbinary' or smth like that, or vice versa. Try to find it, on tables that you update in this call to SaveChanges. 
I am wondering - where all these DbType/DbTypeSpec attrs are coming from? was model generated from DB a while ago? I would suggest to remove all these Column attributes with DbTypeSpecs altogether, let fwk manage data types

**Comment by rubenalves** [comment] 2020-01-08 01:14
It looks like it is trying to convert a byte to string or the other WAY around.
All this atributos where for over 2 years. I Will try to remove them all but there are over 200 tables, and can break my app.
It is probably not worth it.

Ruben Alves
________________________________
De: Roman Ivantsov <notifications@github.com>
Enviado: Wednesday, January 8, 2020 12:01:12 AM
Para: rivantsov/vita <vita@noreply.github.com>
Cc: rubenalves <ruben.alves@serreta.net>; Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] Problems converting to 3.0 (#111)


about first problem, DbTypeSpec = "Binary" - this is invalid, just remove the Column attribute, fwk should assign the correct type
the second error - looks like you have type mismatch on some property, likely string property but DbTypeSpec is 'varbinary' or smth like that, or vice versa. Try to find it, on tables that you update in this call to SaveChanges.
I am wondering - where all these DbType/DbTypeSpec attrs are coming from? was model generated from DB a while ago? I would suggest to remove all these Column attributes with DbTypeSpecs altogether, let fwk manage data types

**Comment by rivantsov** [comment] 2020-01-08 04:50
probably something was lost in conversion to this version, I assume you did some string-replace Dbtype -> DbTypeSpec. I would suggest to carefully go thru all entities and fix things - it's worth it, for the future. and you need to find and fix this bug

**Comment by rubenalves** [comment] 2020-01-08 18:52
Foun the problem,

If i have [Unlimite] on de column definition for Byte[] it gives that error.
Now i have only nullable like this
[Nullable]
        byte[] LogoTalao { get; set; }

        [Nullable]
        byte[] LogoDocumentos { get; set; }
And the save changes gives error,
How can i have a nullable byte[] field?
or what is the correct field type to store a image?
Thanks for your help.

**Comment by rivantsov** [comment] 2020-01-08 19:00
Put [Nullable, Unlimited], that should fix it

**Comment by rubenalves** [comment] 2020-01-08 19:07
Thant was how i hade before, it gives the error:
SqlException: Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.

**Comment by rivantsov** [comment] 2020-01-08 19:16
Ok, then your problem comes at runtime, with the value itself. 
So leave it with Nullable and Unlimited, and let's find what value is breaking it. How you assign the value to this field? 
How many records are saved with SaveChanges? is it batch save or single record save?
Also, if you have logfile setup, it should contain error message AND SQL that was attempted, with some parameters listed.  Let's see the SQL if possible. Is the logo really tiny? I'm wondering if it happens because byte array is tiny and db engine decides to put the value as literal, and literal is interpreted by SQL server as string

**Comment by rubenalves** [comment] 2020-01-08 21:31
Byte [] column whas created as varbinary(max) on version 1.9 now it is getting created as varbinary(128)
that probably is one of the reasons for the conversio error that i am getting.

**Comment by rubenalves** [comment] 2020-01-08 21:32
I am leaving this columns with no value on insert.

**Comment by rivantsov** [comment] 2020-01-08 21:37
oh no, it shouldn't be. If you put [Nullable, Unlimited] and allow schema update, it should create varbinary(max). Pls verify it.
I do not think this is the reason for conv error, it is different kind of error; somewhere somehow, during actual data insert the byte[] value arrives as string/varchar - we need to see the SQL that was sent. Pls look at SQL log, or - you should be able to see in inside exception, inside Exc.DAta dictionary

**Comment by rubenalves** [comment] 2020-01-08 21:39
It is creating varbinary(128)

**Comment by rivantsov** [comment] 2020-01-08 22:02
sounds strange, I will try to repro it later. What about SQL that fails?

**Comment by rubenalves** [comment] 2020-01-08 22:06
How can i get the sql that is sent?
i only get a error.

**Comment by rivantsov** [comment] 2020-01-08 22:15
see above, either setup log to file (and lookup there), or catch exc in debugger and look into exc.Data dictionary

**Comment by rubenalves** [comment] 2020-01-08 23:21
Sorry,
I am very basic with visual studio, i cant find a way to catch the exc in the debugger and do know how to setup log to file.
Will wait to see if you can find the problem with the varinary(128)
Thanks

**Comment by rivantsov** [comment] 2020-01-08 23:24
to setup log to file - assign EntityApp.LogFilePath = "myLog.txt", file will appear in bin folder of your app. Look at ExtendedTests project in unit tests, Startup.cs file, it does this and after running tests - see log file in bin folder

**Comment by rivantsov** [comment] 2020-01-08 23:43
I think varbinary(128) is a separate problem; check - are you setting Size on this column anywhere? try the following - drop the column in the database and rerun the test - see if it is re-created correctly. 
For update statement - lets try with batching disabled; at startup set
dbSettings.ModelConfig.Options &= ~DbOptions.UseBatchMode; 
and run the test again.

**Comment by rubenalves** [comment] 2020-01-09 00:11
I drop the database and vita recreated it every time until it gives no error bacause it has to inserts lots of data to the database 
I canot disable the batch mode,
dbSettings.ModelConfig.Options &= ~DbOptions.UseBatchMode;
dos not compile.

**Comment by rubenalves** [comment] 2020-01-09 00:57
I managed to make the log file
[log.txt](https://github.com/rivantsov/vita/files/4038044/log.txt)
Thanks.

**Comment by rivantsov** [comment] 2020-01-09 04:31
great! I would like to see the full definition of this FormsHeader entity

**Comment by rubenalves** [comment] 2020-01-09 11:52
[FormHeader.txt](https://github.com/rivantsov/vita/files/4040224/FormHeader.txt)

Here is the definition file.
Thanks.

**Comment by rivantsov** [comment] 2020-01-09 15:15
Ok, thx, that's quite a table... few questions. What is ImagemSize (type)? 
also, can you pls send db table script (generate script in SQL mgmt studio)?

**Comment by rivantsov** [comment] 2020-01-09 15:18
Also, regarding this varbinary(max); can you pls install sources and run ExtendedTests, and look at book.Image table, Data column - it should be [varbinary(max), null]. Then delete this column, rerun the tests - fwk should restore it, with the same type. If it works as expected, then let's see what's different in your table

**Comment by rubenalves** [comment] 2020-01-09 16:17
It is a enum column

public enum ImagemSize
    {
        Auto,
        Centrado,
        Normal,
        Esticado,
        EsticadoProporcional
    }
[FormHeaderSQL.txt](https://github.com/rivantsov/vita/files/4041336/FormHeaderSQL.txt)

Here is the Generated Script in SQL Managment Studio.
Thanks.

**Comment by rivantsov** [comment] 2020-01-09 18:36
also pls try the following. There are 2 columns of type byte[], LogoTalao and LogoDocumentos. So try assigning something before you save: 
ent.LogoTalao = new byte[] {1, 2, 3};
same for other column
and see if it fails

**Comment by rivantsov** [comment] 2020-01-09 19:19
by the way, looking at SQL log, looks like you're doing quite wild stuff there, at startup. Creating stored procs and functions, replacing columns with computed columns, and TRIGGERS! so my first question would be - is there any script like this that involves this table? pls double-check there are no triggers for this table. In general, I would suggest to get rid of triggers, they are a source of trouble, and current dev practices strongly suggest to avoid using them.

**Comment by rubenalves** [comment] 2020-01-09 19:29
That is a simple table that does not hove no modifications at db creation,

Those modificatiosn work very well with vertion 1.9 and do not give any errors.

I am trying to run the unit testes project that you sugested and i canot run the tests, will try some more to see.

**Comment by rubenalves** [comment] 2020-01-09 20:50
Thatis a simple table that does nothove no modifications at db creation,

Thosemodificatiosn work very well with vertion 1.9 and do notgive any errors.

I am trying to run the unit testes project thatyou sugested and i canot run the tests, will try some more to see.


Com os melhores cumprimentos,

Ruben Alves
Móvel: 916887379
Email: ruben.alves@outlook.pt

De: Roman Ivantsov <notifications@github.com>
Enviada: 9 de janeiro de 2020 18:20
Para: rivantsov/vita <vita@noreply.github.com>
Cc: rubenalves <ruben.alves@serreta.net>; Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] Problems converting to 3.0 (#111)


by the way, looking at SQL log, looks like you're doing quite wild stuff there, at startup. Creating stored procs and functions, replacing columns with computed columns, and TRIGGERS! so my first question would be - is there any script like this that involves this table? pls double-check there are no triggers for this table. In general, I would suggest to get rid of triggers, they are a source of trouble, and current dev practices strongly suggest to avoid using them.

**Comment by rubenalves** [comment] 2020-01-09 21:25
I have managed to get the tests to run,
the books.image.data gest created as varbinary(max) , not null

I know that trigers are a source of problemas if they as not well implemented, but those trigers are on over 150 databases for over 2 years with no problem.

Will try to change my table to help discover what the error is causing the error.
Thanks

**Comment by rivantsov** [comment] 2020-01-09 21:30
ok, no problem, forget about triggers, let's try assigning some values to these 2 columns, see how it goes. We have error message that mentions varbinary, but does not tell column name or parameter name. We have just 2 columns of varbinary, so let's play with these. 
By the way, you have a lot of decimal columns. I would understand decimal for money columns, but for other things? did you migrate from Oracle?

**Comment by rubenalves** [comment] 2020-01-09 21:32
I did not micrete from Pracle, and yes the decimal are for money and othe precise calculation values.

**Comment by rubenalves** [comment] 2020-01-09 21:40
If i initialise the columns with new byte[] {1, 2, 3}; it works perfectly.

**Comment by rivantsov** [comment] 2020-01-09 21:43
al rite, something to work with. I will run some tests around this, will let you know. Also, pls put back Unlimited on these 2 columns, and see if you can create them as varbinary(max)

**Comment by rubenalves** [comment] 2020-01-09 22:06
I have put the Unlimited and now it shows varbinary(max) null

If i do not assign it new byte[] {1, 2, 3}; it does not work.
the seems to be a problem with the nullable byte[] very stransge problem.

**Comment by rivantsov** [comment] 2020-01-09 23:42
Great! one problem solved, and now we have narrow case, looks like problem is with Null value in varbinary. I think I don't have a test case for this, and this might be the problem. Will test it and let you know

**Comment by rivantsov** [comment] 2020-01-10 00:50
reproduced it, will be checking fix soon.

**Comment by rivantsov** [comment] 2020-01-10 07:48
fixed, pushed v 3.0.1

**Comment by rubenalves** [comment] 2020-01-10 13:09
OK. Thank you very much.

Just a nother question.

How can i convert this
[AsIs, NoInsertUpdate, Nullable]
 decimal QtdEntradas { get; }

NoInsertUpdate is not available now, that is for those columns altered by the triggers
Thank you so much.

**Comment by rubenalves** [comment] 2020-01-10 13:16
I fou a solution, Readony does the job.
Thanks.

**Comment by rubenalves** [comment] 2020-01-10 13:20
Are you planing to get back the CacheSettings?

App.CacheSettings.CacheEnabled = true;

**Comment by rivantsov** [comment] 2020-01-10 14:12
I am planning bring back data caching, will rebuild it
Let's close this thread, it became bit too long, continue on a fresh one

**Closed by rivantsov** 2020-01-10 14:12 UTC
