### ISSUE TITLE
Build 1.9.0

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#10] opened 2016-10-07 12:53 UTC
I have updated to 1.9.0 and my application does not work but i does not give any error, it just hangs, whas there any breaking changes to this version?

**Comment by rivantsov** [comment] 2016-10-07 14:48
yeah, there were some changes. It hangs when, which method?

**Comment by rubenalves** [comment] 2016-10-07 14:50
I will try debug step by step to find out wich.

**Comment by rubenalves** [comment] 2016-10-08 11:18
It hangs after 

DbChangedModule.Init();

**Comment by rivantsov** [comment] 2016-10-08 15:32
can't quite locate it, can you pls be more specific? what if you just wait until it hangs, then click Pause button (on debug toolbar), and it will show you exact location and call stack. (provided you enabled stepping in and disabled 'Just my code' in options). Can you then copy and send me the call stack and any related info?

**Comment by rubenalves** [comment] 2016-10-09 00:43
I have tried it but when i hit pause it has no relevant info.

I have disabeld DbUpgradeLogModule and it works fine so for me it is not a problem now.
I will try it again and see if i can find  some info to help.

Do you have a list of what was changed or added in this new version?

**Comment by rivantsov** [comment] 2016-10-10 18:21
lots of things changed, mostly internally. Do not recall anything change for this module. Will have a look into it and see what potentially can be causing hanging like this

**Comment by rubenalves** [comment] 2016-10-10 22:04
I disabled DbUpgradeLogModule and the application starts ok, if i make any change that it has to update the database and log changes it hangs, but if i close it and start it again the changes where applied.

Very strange.
Looks like it was something to do with logging.

**Comment by rivantsov** [comment] 2016-10-10 22:16
hmm.. interesting, I'm looking at tables, nothing suspicious. Try dropping tables log.DbUpgradeScript, log.DbUpgradeBatch in log database, and see how it behaves then. Check if tables appear, and if records in them appear.

**Comment by rivantsov** [comment] 2016-10-18 19:35
did you make it work? still happening? can you give me some more info? I use lock() statement there, might be under suspicion that this is the problem, but cannot reproduce anything...

**Comment by rubenalves** [comment] 2016-10-20 00:01
I had to revert to the previous version because i cannot wait more for a new release i need to make.

Is there any way to make the framework thow when it findes a error? it is much metter than simply hanging.

Regards,

**Comment by rubenalves** [comment] 2017-01-03 21:52
Is there any way to make the framework thow when it findes a error? it is much metter than simply hanging.

Regards

**Comment by rivantsov** [comment] 2017-01-03 22:02
of course it's better than throwing; certainly I'm not doing it on purpose. I am just have little idea what causes hanging in your case - cannot repro it. 
Just hang on for a little more, I am rounding up new version, there will be some refactoring in this area, plus selective selection of logging modules, so you can disable this part if it still does not work
Sorry  for troubles

**Comment by rubenalves** [comment] 2017-01-03 22:14
Ok, no problem. Thanks

**Comment by rubenalves** [comment] 2017-01-03 23:42
One more thing i noticed, if i create a calculated field and add  the {get; set;} vita hangs and does not thow, if i remove the set; it works fine, so probably it is related to my other problem?

Regards

**Comment by rivantsov** [comment] 2017-01-04 04:38
hm, that's interesting, let me look at this. thanks for the tip

**Comment by rivantsov** [comment] 2017-01-04 18:58
Ok, here's what I found. I think you meant using "Computed" attribute on a property. So if I add "settter" on such property, the startup fails - throws TypeLoad exception, saying that Ent.set_PropName property has no implementation in the class. It does not hang in my case. I went back to the 1.9 version, and it is still like this, no hangs. (Yes, it is handled improperly, it should be detected and properly reported by ModelBuilder). Do I miss something or do a different thing from what you have?  
I just modified FullName property of IAuthor entity in BookStore sample: 

    [Computed(typeof(BooksModule), "GetFullName"), DependsOn("FirstName,LastName")] //DependsOn is optional, used for auto PropertyChanged firing
    string FullName { get; set; } 

thanks

**Comment by rubenalves** [comment] 2017-01-04 23:59
Yes, that is what i ment, but on my PC it does not throw in just hangs.

Thanks

**Comment by rivantsov** [comment] 2017-01-05 19:28
Ok, I think we have something here, we found the cause of the problem. It looks like the cause of hangs is this improperly declared computed property; just on your computer is results in hanging instead of type load exc as it happens on mine. It would be interesting to find out why, but no emergency for this. The important thing is that we can fix the hanging. I will provide a fix (model builder will throw error) in the next push. 
Thanks!

**Comment by rivantsov** [comment] 2017-02-05 18:06
should be fixed now, pls try upgrading to 1.9.2. You can also enable logging modules selectively

**Comment by rivantsov** [comment] 2017-02-09 18:20
Hi, did you try to upgrade?

**Comment by rubenalves** [comment] 2017-02-09 18:30
I will try today.

Thanks

De: Roman Ivantsov [mailto:notifications@github.com]
Enviada: 9 de fevereiro de 2017 17:20
Para: rivantsov/vita <vita@noreply.github.com>
Cc: rubenalves <ruben.alves@serreta.net>; Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] Build 1.9.0 (#10)


Hi, did you try to upgrade?

**Comment by rubenalves** [comment] 2017-02-09 22:09
It is working now, it was something realted with DbUpgradeLogModule, disabled it and now it does not hang. I do not that module so it is all ok now.

**Comment by rubenalves** [comment] 2017-02-11 04:24
I see 
Bug fix: Views requiring Order-By clause - fixed. 
in 1.9 but i canot use, i get a error that it is not supported, how can i make a order by in a view?
I can do it manualy with no problem

Regards.

**Comment by rivantsov** [comment] 2017-02-11 04:41
can you pls give some more info? give a view def and error that you get

**Comment by rivantsov** [comment] 2017-02-11 05:34
Ok, looks like Views with Order by are supported in MS SQL with some restrictions. When I try to create the following view (directly in SQL studio): 
CREATE VIEW "books"."vFictionBook"   AS 
  -- HASH:*0C5927E12A06666FDE73ED8468EC798D*
SELECT "Id", "CreatedOn", "Title", "Description", "PublishedOn", "Abstract", "Category", "Editions", "Price", "CreatedIn", "UpdatedIn", "Publisher_Id", "CoverImage_Id", "Editor_Id"
FROM "books"."Book"
WHERE ("Category" = 1)
ORDER BY "Title"

I get error from SQL Server: 
The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.

I guess what you get is error from SQL Server. When you say you can do it manually - what's the SQL you run?

**Comment by rubenalves** [comment] 2017-02-11 14:06
Sorry,

I was using TOP that it why it was working, so ignore my mistake.

Regards,
Ruben

De: Roman Ivantsov [mailto:notifications@github.com]
Enviada: 11 de fevereiro de 2017 04:34
Para: rivantsov/vita <vita@noreply.github.com>
Cc: rubenalves <ruben.alves@serreta.net>; Author <author@noreply.github.com>
Assunto: Re: [rivantsov/vita] Build 1.9.0 (#10)


Ok, looks like Views with Order by are supported in MS SQL with some restrictions. When I try to create the following view (directly in SQL studio):
CREATE VIEW "books"."vFictionBook" AS
-- HASH:0C5927E12A06666FDE73ED8468EC798D
SELECT "Id", "CreatedOn", "Title", "Description", "PublishedOn", "Abstract", "Category", "Editions", "Price", "CreatedIn", "UpdatedIn", "Publisher_Id", "CoverImage_Id", "Editor_Id"
FROM "books"."Book"
WHERE ("Category" = 1)
ORDER BY "Title"

I get error from SQL Server:
The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.

I guess what you get is error from SQL Server. When you say you can do it manually - what's the SQL you run?

**Closed** 2017-02-13 20:08 UTC
